#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

load 'make-html-common'

def usage
	puts <<USAGE
Usage:
  make-html-index

Options:
  -d, --debug   : debuging
USAGE
	exit
end

# re-generate all if nothing
if ARGV.empty?
  $DEBUG = true
  Dir["#$here/html/chap*.html"].each do |file|
    ARGV.push(file)
  end
end

figures do
  config = $config['default'].merge($config["ko"]) rescue $config['default']
  
  print "\tCreating index.html ... " if $DEBUG
  File.open("#$here/html/index.html", 'w') do |file|
    html = "<ul>\n"
    ARGV.sort.map do |path|
      chap = /chap(\d+)/.match(path)[1]
      date = html_mtime(chap)
      link = path["#$here/html/".length..-1]
      
      info = {
        "title" => "",
        "abstract" => "",
      }
      
      # extract info
      markdown = File.read("#$here/chap#{chap}/doc.markdown")
      info.each_key do |key|
        blob = markdown.scan(/^% #{key}:(.*)/).join
        blob.gsub("\n", "")
        info[key] = blob
      end

      html += <<DONE
<li>
  <article class="post">
    <header>
      <h3>
        <span class="hint">Chap ##{chap}</span>
        #{date}
      </h3>
      <h1>
        <a href="#{link}">#{info["title"]}</a>
      </h1>
     </header>
     <p>#{info["abstract"]}</p>
  </article>
</li>
DONE
    end
    html += "</ul>"
    
    template = $index_template.result(binding)
    file.write($base_template.result(binding))
  end
  puts "done" if $DEBUG
end
