#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

$LOAD_PATH.push("script")

load 'make-html-common'

def usage
	puts <<USAGE
Usage:
  make-html [markdown]

Options:
  -d, --debug   : debuging
USAGE
	exit
end

# re-generate all if nothing
if ARGV.empty?
  $DEBUG = true
  Dir["#$here/chap*/doc.markdown"].each do |file|
    ARGV.push(file)
  end
end

# load history
deps = {}
if File.exist?(".snap-dep")
  deps = eval(File.read(".snap-dep"))
end


def in_dir(dir, &block)
  old = pwd()
  cd(dir)
  block.call
  cd(old)
end

ARGV.sort.map do |file|
  chap = /chap(\d+)/.match(file)[1]
  puts "  [!] Reading markdown #{file}" if $DEBUG

  snap = `./make-md -s #{file}`
  snap and snap.each do |line|
    line = line.rstrip
    puts "  [!] #{line}" if $DEBUG
      
    # image output
    out = /-o ([^ ]+)/.match(line)[1]
    
    # check if exist
    if deps[out] != line or !File.exist?("img/" + out)
      system(line.gsub(out, "img/" + out))
      deps[out] = line
    end
  end
end

# update dependencies
File.open(".snap-dep", "w") do |f|
  f.write(deps.inspect)
end
