#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

load 'make-html-common'

$pandoc = <<END
pandoc -f markdown -t json \
 | runhaskell pygments.hs \
 | pandoc -s -p --no-wrap -f json -t html
END

def usage
	puts <<USAGE
Usage:
  make-html [markdown]

Options:
  -d, --debug   : debuging
USAGE
	exit
end

# re-generate all if nothing
if ARGV.empty?
  $DEBUG = true
  Dir["#$here/chap*/doc.markdown"].each do |file|
    ARGV.push(file)
  end
end

figures do
  config = $config['default'].merge($config["ko"])

  ARGV.sort.map do |file|
    markdown = File.read(file)
    print "\tParsing markdown #{file}" if $DEBUG
    
    html = pipe("pandoc -f markdown -t json \
                    | runhaskell #$here/script/pygments.hs \
                    | pandoc -s -p --no-wrap -f json -t html") do |stdin, stdout, stderr|
      stdin.write(pre_pandoc(markdown, config))
      stdin.close
      post_pandoc(stdout.read, config)
    end

    chap = /chap(\d+)/.match(file)[1]
    date = html_mtime(chap)
    File.open("#$here/html/chap#{chap}.html", 'w') do |file|
      template = $chap_template.result(binding)
      file.write($base_template.result(binding))
    end
  end
  puts " ... done" if $DEBUG
end
