#!/bin/bash

ROOT=`dirname $0`
PORT=":11"

kill_vnc() {
    vncserver -kill $PORT &> /dev/null
}

kill_vnc
vncserver $PORT -geometry 1024x768 

DISPLAY=$PORT $ROOT/snap.rb $@

# just in case to debug
sleep 1
DISPLAY=$PORT import -window root screen.jpg

kill_vnc
