#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# . /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
gnome-settings-daemon &
gnome-terminal &
metacity &
